# -*- coding: utf-8 -*-
"""Seed regulation data aligned with the PRD v1.0 regulation field dictionary, section 9.3.

Field definitions (PRD):
  regulation_id / name / official_number / issuer / type / scope /
  applicable_product / effective_date / impact_level / core_requirement /
  official_source / last_verified_at / status / version
Business extensions aligned with the regulation support workbook and customer support gap matching:
  provide (materials required from Chinese manufacturers, P0–P3) / local_duty (local partner responsibilities) /
  gap (compliance gaps) / scenarios (business use cases linked to the customer support page)
"""

# Regulation type values (PRD type field).
REG_TYPES = ["Access Certification", "Battery Compliance", "Cybersecurity", "Data and AI", "Carbon Compliance", "Emissions Compliance", "Materials Compliance", "Public Procurement", "Safety Assessment"]
# Applicable scope values (PRD scope field).
SCOPES = ["EU-wide", "EU and 60+ contracting parties including the United Kingdom", "EU imports", "EU public procurement", "Member State: Germany", "Member State: France"]
# Business use cases linked to client_type and scenario on the customer support page.
SCENARIOS = ["Public Transit Operator", "Logistics Fleet", "Corporate Fleet", "Government", "Mobility Platform", "Charging Infrastructure"]

REGULATIONS = [
  {
    "regulation_id": "REG-001",
    "name": "EU Battery Regulation",
    "official_number": "(EU) 2023/1542",
    "issuer": "European Commission",
    "type": "Battery Compliance",
    "scope": "EU-wide",
    "applicable_product": ["Vehicles", "Buses", "Traction batteries"],
    "effective_date": "2024-02-18 (phased requirements: due diligence from 2025-08; battery passports from 2027)",
    "impact_level": "High",
    "core_requirement": "Requires battery passports, carbon-footprint declarations, supply-chain due diligence, and recycled-content information. Due-diligence duties begin in August 2025; battery passports become a key requirement for EV and industrial batteries from 2027.",
    "official_source": "https://eur-lex.europa.eu/eli/reg/2023/1542/oj/eng",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("Digital battery passport data", "P0"), ("Life-cycle carbon-footprint report", "P0"),
      ("Mineral supply-chain due-diligence report", "P0"), ("Battery durability report: 8 years / 72% state of health", "P1"),
      ("Recycled-content evidence", "P1"),
    ],
    "local_duty": "Integrate the battery system into the local vehicle model and submit a vehicle-level sustainability statement with the tender.",
    "gap": "Confirm whether all required battery-passport fields are available for the target batteries and partner vehicle models. Upstream supplier carbon data may be incomplete.",
    "scenarios": ["Public Transit Operator", "Logistics Fleet", "Government", "Mobility Platform"],
  },
  {
    "regulation_id": "REG-002",
    "name": "AFIR Alternative Fuels Infrastructure Regulation",
    "official_number": "(EU) 2023/1804",
    "issuer": "European Commission",
    "type": "Infrastructure",
    "scope": "EU-wide",
    "applicable_product": ["Charging infrastructure", "Buses", "Heavy-duty vehicles"],
    "effective_date": "2024-04-13",
    "impact_level": "High",
    "core_requirement": "Requires at least 150 kW fast-charging stations every 60 km along TEN-T roads and at least 350 kW charging stations for heavy-duty vehicles. Charging interoperability, convenient payment, and transparent pricing are also required.",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32023R1804",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("Charging equipment interoperability test report", "P0"), ("Pricing transparency compliance statement", "P1"),
      ("Fast-charger deployment quota plan", "P1"), ("Power-grid data exchange compliance evidence", "P2"),
    ],
    "local_duty": "Coordinate local charging-site deployment and operations, and integrate vehicles and charging into a unified tender proposal.",
    "gap": "A local charge-point operator or utility partner may be required. Depot-charging schedules and energy-storage plans are not yet standardized.",
    "scenarios": ["Public Transit Operator", "Logistics Fleet", "Charging Infrastructure"],
  },
]
REGULATIONS += [
  {
    "regulation_id": "REG-003",
    "name": "EU Artificial Intelligence Act AI Act",
    "official_number": "(EU) 2024/1689",
    "issuer": "European Parliament and Council",
    "type": "Data and AI",
    "scope": "EU-wide",
    "applicable_product": ["Vehicles", "Software", "Smart cockpits"],
    "effective_date": "2024-08-01 (phased high-risk in-vehicle AI obligations through 2027-12)",
    "impact_level": "Medium",
    "core_requirement": "High-risk AI systems require risk management, technical documentation, test records, and human oversight. Users must be informed about emotion-recognition systems. Obligations for high-risk AI used as vehicle safety components are being phased in.",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("In-vehicle high-risk AI use-case registration", "P1"), ("Algorithm explainability evidence", "P1"),
      ("AI privacy and bias risk assessment report", "P1"), ("Human-machine safety interaction statement", "P2"),
      ("Model card documenting training data and bias", "P2"),
    ],
    "local_duty": "Determine the intended use of the AI feature in the vehicle or operational setting and confirm whether it falls into a high-risk category.",
    "gap": "Confirm whether ADAS or cockpit emotion-recognition features trigger high-risk obligations. Explainability and human-oversight records are missing.",
    "scenarios": ["Mobility Platform", "Corporate Fleet", "Government"],
  },
  {
    "regulation_id": "REG-004",
    "name": "UNECE R155 Vehicle Cybersecurity",
    "official_number": "UN R155 / CSMS",
    "issuer": "UNECE WP.29",
    "type": "Cybersecurity",
    "scope": "EU and 60+ contracting parties including the United Kingdom",
    "applicable_product": ["Vehicles", "Connected-vehicle systems"],
    "effective_date": "2024-07-01 (mandatory for all newly produced vehicles)",
    "impact_level": "High",
    "core_requirement": "Requires an organization-level CSMS certificate (valid for up to three years) and vehicle type certification. Manufacturers must conduct TARA threat analysis, monitor the vehicle throughout its lifecycle, and secure the supply chain, following ISO/SAE 21434.",
    "official_source": "https://unece.org/sites/default/files/2023-02/R155e%20%282%29.pdf",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("CSMS cybersecurity management system certificate", "P0"), ("Vehicle TARA threat assessment report", "P0"),
      ("Vulnerability discovery, disclosure, and response process", "P1"), ("Interface security statement", "P1"), ("Penetration test report", "P2"),
    ],
    "local_duty": "Coordinate vehicle-level cybersecurity and type-certification submissions.",
    "gap": "Confirm whether the TARA covers systems supplied by the Chinese manufacturer and can integrate with the local vehicle manufacturer's CSMS.",
    "scenarios": ["Public Transit Operator", "Logistics Fleet", "Government", "Mobility Platform", "Corporate Fleet"],
  },
  {
    "regulation_id": "REG-005",
    "name": "UNECE R156 Software Update Management",
    "official_number": "UN R156 / SUMS",
    "issuer": "UNECE WP.29",
    "type": "Cybersecurity",
    "scope": "EU and 60+ contracting parties including the United Kingdom",
    "applicable_product": ["Vehicles", "Over-the-air update systems"],
    "effective_date": "2024-07-01",
    "impact_level": "Medium",
    "core_requirement": "Software updates must be controlled, traceable, and safely reversible. The regulation requires a certified software update management system (SUMS) and compliant over-the-air update processes.",
    "official_source": "https://unece.org/transport/documents/2021/03/standards/un-regulation-no-156-software-update-and-software-update-management",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("SUMS documentation", "P0"), ("Over-the-air update process documents", "P1"),
      ("Software version records", "P1"), ("Rollback mechanism statement", "P2"),
    ],
    "local_duty": "Coordinate vehicle-level software update certification and customer delivery documentation.",
    "gap": "Confirm whether the Chinese manufacturer's software update process can be included in the local partner's SUMS. Release and rollback responsibilities need clarification.",
    "scenarios": ["Public Transit Operator", "Mobility Platform", "Corporate Fleet"],
  },
  {
    "regulation_id": "REG-006",
    "name": "GDPR + EU Data Act Data Act",
    "official_number": "(EU) 2023/2854",
    "issuer": "European Commission",
    "type": "Data and AI",
    "scope": "EU-wide",
    "applicable_product": ["Vehicles", "Fleet platforms", "Connected vehicles"],
    "effective_date": "2025-09-12 (Data Act applies)",
    "impact_level": "High",
    "core_requirement": "From September 2025, connected-vehicle data must be portable and users must be able to authorize third-party access. Connected-vehicle risk assessments must also account for GDPR and NIS2.",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32023R2854",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("Data-flow diagram and data-field inventory", "P0"), ("Data protection impact assessment (DPIA)", "P0"),
      ("Cross-border transfer documentation (SCC/BCR)", "P0"), ("Third-party access authorization mechanism", "P1"), ("EU data-residency statement", "P1"),
    ],
    "local_duty": "Explain data-compliance obligations to end customers and operators, include them in contracts, and confirm controller and processor roles.",
    "gap": "Data sovereignty can be a decisive factor in public procurement. Even when cloud infrastructure is in the EU, remote access to data from outside the region may raise concerns.",
    "scenarios": ["Government", "Public Transit Operator", "Mobility Platform", "Corporate Fleet"],
  },
]
REGULATIONS += [
  {
    "regulation_id": "REG-007",
    "name": "CBAM Carbon Border Adjustment Mechanism",
    "official_number": "(EU) 2023/956",
    "issuer": "European Commission",
    "type": "Carbon Compliance",
    "scope": "EU imports",
    "applicable_product": ["Upstream materials (steel/aluminium)", "Supply chains"],
    "effective_date": "2026-01-01 (definitive phase begins)",
    "impact_level": "Medium",
    "core_requirement": "The definitive phase begins in 2026. Current coverage focuses on upstream materials such as iron and steel, aluminium, cement, fertilisers, hydrogen, and electricity, affecting automotive supply-chain carbon costs and disclosures.",
    "official_source": "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism_en",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("Scope 3 value-chain carbon accounting evidence", "P1"), ("Upstream steel and aluminium carbon data", "P1"),
      ("Third-party carbon verification report", "P2"), ("Annual emissions declaration ledger", "P2"),
    ],
    "local_duty": "Set up the EU carbon account, file and settle annual CBAM declarations, and coordinate carbon verification.",
    "gap": "CBAM does not currently apply to all finished-vehicle or battery imports. It affects the carbon cost of covered upstream materials, and vehicle-level carbon traceability remains incomplete.",
    "scenarios": ["Logistics Fleet", "Public Transit Operator"],
  },
  {
    "regulation_id": "REG-008",
    "name": "Euro 7 emissions and battery durability regulation",
    "official_number": "(EU) 2024/1257",
    "issuer": "European Commission",
    "type": "Emissions Compliance",
    "scope": "EU-wide",
    "applicable_product": ["Vehicles", "Commercial vehicles"],
    "effective_date": "2026-11-29 (mandatory for new vehicle types)",
    "impact_level": "Medium",
    "core_requirement": "Mandatory for new vehicle types from late 2026. Tightens brake and tyre particle-emission limits and introduces a minimum traction-battery durability standard of 72% capacity retention after eight years.",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=OJ:L_202401257",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("Vehicle particle-emissions test report", "P1"), ("Zero-emission fleet compliance evidence", "P1"),
      ("Traction-battery durability verification", "P1"), ("Exhaust monitoring system compliance statement", "P2"),
    ],
    "local_duty": "Coordinate vehicle environmental type approval and market access.",
    "gap": "Battery durability and brake/tyre particle-emissions testing have not yet been completed against the latest European standards.",
    "scenarios": ["Logistics Fleet", "Public Transit Operator", "Corporate Fleet"],
  },
  {
    "regulation_id": "REG-009",
    "name": "EU CO₂ Emission Standards for Cars and Vans",
    "official_number": "CO₂ Standards",
    "issuer": "European Commission",
    "type": "Emissions Compliance",
    "scope": "EU-wide",
    "applicable_product": ["Passenger cars", "Vans"],
    "effective_date": "Phased targets for 2025, 2030, and 2035",
    "impact_level": "High",
    "core_requirement": "For 2025–2029, emissions targets are 15% below the 2021 baseline. By 2030, targets are 55% lower for cars and 50% lower for vans. From 2035, new cars and vans must achieve a 100% reduction, ending sales of new combustion-engine vehicles.",
    "official_source": "https://climate.ec.europa.eu/eu-action/transport-decarbonisation/road-transport/cars-and-vans_en",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("Fleet TCO and emissions calculation template", "P1"), ("Vehicle CO₂ compliance data", "P1"),
      ("Use-case emissions messaging for government, taxi, and logistics fleets", "P2"),
    ],
    "local_duty": "Prepare the vehicle tender response for green procurement requirements.",
    "gap": "Develop separate product configurations for passenger cars, vans, and buses; a single vehicle model cannot serve every use case.",
    "scenarios": ["Corporate Fleet", "Mobility Platform", "Government", "Logistics Fleet"],
  },
  {
    "regulation_id": "REG-010",
    "name": "Regulation 2018/858 Vehicle Type Approval (WVTA)",
    "official_number": "(EU) 2018/858",
    "issuer": "European Commission",
    "type": "Access Certification",
    "scope": "EU-wide",
    "applicable_product": ["Vehicles"],
    "effective_date": "2020-09-01 (M1 approvals are generally valid for about seven years)",
    "impact_level": "High",
    "core_requirement": "Vehicles entering the European market require whole-vehicle type approval (WVTA), a Certificate of Conformity (CoC), and compliance with market-surveillance requirements.",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32018R0858",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("Whole-vehicle type-approval (WVTA) documents", "P0"), ("Certificate of Conformity (CoC)", "P0"),
      ("Component and system technical files and test reports", "P1"), ("Supplier declarations", "P2"),
    ],
    "local_duty": "Coordinate whole-vehicle type approval, CoC, conformity-of-production, and market-access documentation.",
    "gap": "Confirm whether technical changes by the Chinese manufacturer trigger renewed vehicle approval or additional testing.",
    "scenarios": ["Public Transit Operator", "Logistics Fleet", "Government", "Mobility Platform", "Corporate Fleet"],
  },
  {
    "regulation_id": "REG-011",
    "name": "Clean Vehicles Directive Clean Vehicles Directive",
    "official_number": "(EU) 2019/1161",
    "issuer": "European Commission",
    "type": "Public Procurement",
    "scope": "EU PublicProcurement",
    "applicable_product": ["Buses", "Government vehicles", "Vehicles"],
    "effective_date": "2021-08-02",
    "impact_level": "Medium",
    "core_requirement": "Public procurement sets minimum procurement targets for clean and zero-emission vehicles, considering low emissions, total cost of ownership, and environmental performance.",
    "official_source": "https://transport.ec.europa.eu/transport-themes/clean-transport/clean-vehicles-directive_en",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("Battery energy consumption and electric-drive efficiency data", "P0"), ("Emissions reduction calculations", "P1"), ("TCO input data", "P1"),
    ],
    "local_duty": "Prepare vehicle tender responses for green procurement.",
    "gap": "Provide customer-ready energy consumption, emissions reduction, and cost data to support green procurement scoring.",
    "scenarios": ["Public Transit Operator", "Government"],
  },
  {
    "regulation_id": "REG-012",
    "name": "Foreign Subsidies Regulation Foreign Subsidies Regulation",
    "official_number": "(EU) 2022/2560",
    "issuer": "European Commission",
    "type": "Public Procurement",
    "scope": "EU PublicProcurement",
    "applicable_product": ["Vehicles", "Large procurements"],
    "effective_date": "2023-10-12",
    "impact_level": "Medium",
    "core_requirement": "Large public procurement procedures may require disclosure of foreign financial contributions, including subsidies, loans, and guarantees.",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022R2560",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("Foreign financial contributions register", "P1"), ("Subsidy, loan, and guarantee statements", "P1"),
      ("Joint tender responsibility statement", "P2"),
    ],
    "local_duty": "Determine whether the project triggers an FSR notification and coordinate the tender submission.",
    "gap": "Confirm whether the project value and partnership structure trigger FSR disclosure obligations, and whether information from the Chinese partner must be included in the local partner's filing.",
    "scenarios": ["Public Transit Operator", "Government"],
  },
]
REGULATIONS += [
  {
    "regulation_id": "REG-013",
    "name": "General Safety Regulation General Safety Regulation",
    "official_number": "(EU) 2019/2144",
    "issuer": "European Commission",
    "type": "Access Certification",
    "scope": "EU-wide",
    "applicable_product": ["Vehicles", "ADAS"],
    "effective_date": "2024-07-07",
    "impact_level": "High",
    "core_requirement": "Vehicles must meet general EU safety requirements and mandatory fitment requirements for advanced driver-assistance systems (ADAS).",
    "official_source": "https://eur-lex.europa.eu/eli/reg/2019/2144/oj",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("ADAS feature description and safety test report", "P0"), ("Functional safety materials (ISO 26262)", "P1"),
      ("System boundary statement", "P2"),
    ],
    "local_duty": "Coordinate vehicle safety certification and the final safety performance declaration.",
    "gap": "Clarify responsibility boundaries for systems supplied by the Chinese manufacturer and vehicle safety functions. Test reports must meet local customer requirements.",
    "scenarios": ["Public Transit Operator", "Government", "Mobility Platform", "Corporate Fleet"],
  },
  {
    "regulation_id": "REG-014",
    "name": "Euro NCAP 2026 Safety Assessment Protocol",
    "official_number": "Euro NCAP 2026",
    "issuer": "Euro NCAP Consortium",
    "type": "Safety Assessment",
    "scope": "EU-wide",
    "applicable_product": ["Vehicles"],
    "effective_date": "2026-01-01 (updated annually)",
    "impact_level": "Medium",
    "core_requirement": "From 2026, scoring covers four stages: Safe Driving, Crash Avoidance, Crash Protection, and Post-Crash. Each item is scored from 0 to 100%; the lowest-scoring item affects the overall rating.",
    "official_source": "https://www.euroncap.com/protocols/",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("Vehicle structural crash and ADAS test data", "P1"), ("Production consistency documents for test vehicles", "P1"),
      ("Statement on using ratings in tenders", "P2"),
    ],
    "local_duty": "Coordinate with NCAP laboratories, schedule and register tests, validate ratings, and manage communications and appeals.",
    "gap": "The vehicle model has not been adapted to the latest European test standards. Early local assessment is missing, and ADAS compatibility data may limit distribution and tender eligibility.",
    "scenarios": ["Government", "Mobility Platform", "Corporate Fleet", "Public Transit Operator"],
  },
  {
    "regulation_id": "REG-015",
    "name": "REACH / SVHC Chemical Compliance",
    "official_number": "(EC) 1907/2006",
    "issuer": "ECHA",
    "type": "Materials Compliance",
    "scope": "EU-wide",
    "applicable_product": ["Components", "Batteries", "Interiors"],
    "effective_date": "In force",
    "impact_level": "Low",
    "core_requirement": "Materials and chemicals must meet EU substance restrictions. Substances of Very High Concern (SVHCs) must be declared.",
    "official_source": "https://echa.europa.eu/regulations/reach/understanding-reach",
    "last_verified_at": "2026-07-10",
    "status": "Approved",
    "version": "v1.0",
    "provide": [
      ("REACH / SVHC declaration", "P1"), ("Material composition statement", "P2"), ("Supplier compliance declaration", "P2"),
    ],
    "local_duty": "Include supplier declarations in vehicle or component compliance documentation.",
    "gap": "Confirm whether all exported components and repair parts have material-compliance declarations. Upstream data traceability needs improvement.",
    "scenarios": ["Logistics Fleet", "Public Transit Operator", "Corporate Fleet"],
  },
  {
    "regulation_id": "REG-016",
    "name": "German Federal Subsidy and Localization Certification Requirements (Member State Example)",
    "official_number": "DE-KBA / BAFA",
    "issuer": "Germany KBA / BAFA",
    "type": "Access Certification",
    "scope": "Member State: Germany",
    "applicable_product": ["Vehicles", "Buses", "Fleets"],
    "effective_date": "Subsidies declining and local evidence requirements tightening from 2026",
    "impact_level": "High",
    "core_requirement": "Germany adds local subsidy eligibility conditions, localization and maintenance evidence, and charging-infrastructure requirements to the EU framework. Requirements become stricter as subsidies decline.",
    "official_source": "https://www.bafa.de/",
    "last_verified_at": "2026-07-15",
    "status": "Pending Review",
    "version": "v0.9",
    "provide": [
      ("Evidence of German local maintenance network coverage", "P0"), ("Localization, production, or assembly statement", "P1"),
      ("Charging infrastructure evidence (AFIR)", "P1"), ("Subsidy application credentials", "P2"),
    ],
    "local_duty": "Coordinate German local subsidy applications, maintenance-network setup, and localization evidence.",
    "gap": "Member State requirements have not yet been systematically collected. Assign an owner to track German maintenance coverage and subsidy rules, reflecting the policy-change monitoring use case.",
    "scenarios": ["Public Transit Operator", "Government", "Corporate Fleet"],
  },
]
