# -*- coding: utf-8 -*-
"""Generate compliance risk reports and material gap lists without a UI dependency."""
import io
import pandas as pd
from regulations_service import list_regulations, gap_stats, p0_gap_list

IMPACT_ORDER = {"High": 3, "Medium": 2, "Low": 1}


def risk_report_markdown(scope: str = "All Regulations", impact: str = "All", prio_only: str = "All") -> tuple[str, list[dict]]:
    """Generate a compliance risk assessment report and return its source data rows."""
    regs = list_regulations() if scope == "All Regulations" else list_regulations(scope=scope)
    if impact != "All":
        regs = [r for r in regs if r["impact_level"] == impact]
    regs.sort(key=lambda r: -IMPACT_ORDER.get(r["impact_level"], 0))

    lines = [f"# European Market Compliance Risk Assessment Report", f"Scope: {scope} · Impact: {impact} · Generated by the rules engine", ""]
    data = []
    for r in regs:
        risk_map = {"High": "High", "Medium": "Medium", "Low": "Watch"}
        materials = [f"{m}({p})" for m, p in r["provide"]]
        if prio_only == "P0 Only":
            materials = [f"{m}(P0)" for m, p in r["provide"] if p == "P0"]
        lines += [
            f"## {r['name']} ({r.get('official_number','')})",
            f"- Impact: {r['impact_level']} | Risk level: {risk_map.get(r['impact_level'],'Watch')}",
            f"- Core requirement: {r['core_requirement']}",
            f"- Required materials: {', '.join(materials)}",
            f"- Local partner responsibilities: {r.get('local_duty','')}",
            f"- Compliance gap: {r.get('gap','')}" if r.get("gap") else "",
            f"- Official source: {r['official_source']}", "",
        ]
        data.append(r)
    return "\n".join(lines), data


def gap_list_excel() -> bytes:
    """Export material gaps as an Excel byte stream."""
    rows = p0_gap_list() or [{"Notice": "No current gaps"}]
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as w:
        pd.DataFrame(rows).to_excel(w, index=False, sheet_name="Material Gaps")
    return buf.getvalue()
