# -*- coding: utf-8 -*-
"""法规种子数据。字段严格对齐 PRD V1.0 第 9.3 节 Regulation 字段字典。

字段说明(PRD):
  regulation_id / name / official_number / issuer / type / scope /
  applicable_product / effective_date / impact_level / core_requirement /
  official_source / last_verified_at / status / version
业务扩展字段(对齐法规支持.xlsx 主表 + 客户支持缺口联动):
  provide(中国车企需提供材料 P0-P3) / local_duty(本地合作方职责) /
  gap(合规缺口) / scenarios(适用业务场景,用于客户支持页联动)
"""

# 法规类型枚举(PRD type 字段)
REG_TYPES = ["准入认证", "电池合规", "网络安全", "数据与AI", "碳合规", "排放合规", "材料合规", "公共采购", "安全测评"]
# 适用范围枚举(PRD scope 字段)
SCOPES = ["EU 全域", "EU + 英国等 60+ 缔约方", "EU 进口", "EU 公共采购", "成员国:德国", "成员国:法国"]
# 业务场景(与客户支持页 client_type / scenario 联动)
SCENARIOS = ["公共交通", "物流运输", "企业通勤", "政府公务", "出行平台", "充电基础设施"]

REGULATIONS = [
  {
    "regulation_id": "REG-001",
    "name": "EU 电池法规 Battery Regulation",
    "official_number": "(EU) 2023/1542",
    "issuer": "欧盟委员会",
    "type": "电池合规",
    "scope": "EU 全域",
    "applicable_product": ["整车", "公交", "动力电池"],
    "effective_date": "2024-02-18(分阶段:2025/08 尽调,2027 电池护照)",
    "impact_level": "高",
    "core_requirement": "强制电池护照、碳足迹声明、供应链尽职调查、可回收材料含量;2025/08 起尽调义务,2027 起 EV/工业电池电池护照成为关键要求。",
    "official_source": "https://eur-lex.europa.eu/eli/reg/2023/1542/oj/eng",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("数字电池护照数据", "P0"), ("LCA 碳足迹报告", "P0"),
      ("矿产供应链尽职调查报告", "P0"), ("电池 8 年 72% SOH 耐久检测报告", "P1"),
      ("再生材料含量证明", "P1"),
    ],
    "local_duty": "将电池系统整合进本地车型,并在投标中提交整车层面可持续性说明。",
    "gap": "需确认电池护照字段是否完整、是否覆盖目标电池型号和合作车型;上游供应商碳数据链条可能不完整。",
    "scenarios": ["公共交通", "物流运输", "政府公务", "出行平台"],
  },
  {
    "regulation_id": "REG-002",
    "name": "AFIR 替代燃料基础设施法规",
    "official_number": "(EU) 2023/1804",
    "issuer": "欧盟委员会",
    "type": "基础设施",
    "scope": "EU 全域",
    "applicable_product": ["充电设施", "公交", "重卡"],
    "effective_date": "2024-04-13",
    "impact_level": "高",
    "core_requirement": "TEN-T 主干路每 60km 部署至少 150kW 快充;重型车充电站最低 350kW;要求充电互通、支付便利、定价透明。",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32023R1804",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("充电设备互通兼容性检测报告", "P0"), ("定价透明合规说明书", "P1"),
      ("高速充电桩部署配额匹配方案", "P1"), ("电网数据交互合规证明", "P2"),
    ],
    "local_duty": "负责本地充电场站部署与运营对接,整合车辆+充电一体化投标方案。",
    "gap": "需绑定本地 CPO / 电网公司;depot 充电排班与储能方案尚未标准化。",
    "scenarios": ["公共交通", "物流运输", "充电基础设施"],
  },
]
REGULATIONS += [
  {
    "regulation_id": "REG-003",
    "name": "EU 人工智能法案 AI Act",
    "official_number": "(EU) 2024/1689",
    "issuer": "欧盟议会与理事会",
    "type": "数据与AI",
    "scope": "EU 全域",
    "applicable_product": ["整车", "软件", "智能座舱"],
    "effective_date": "2024-08-01(高风险车载 AI 义务分阶段至 2027/12)",
    "impact_level": "中",
    "core_requirement": "高风险 AI 系统需风险管理、技术文档、测试记录与人类监督;情感识别须明确告知;作为车辆安全组件的高风险 AI 义务分阶段实施。",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("车载高风险 AI 场景备案文件", "P1"), ("算法可解释性证明", "P1"),
      ("AI 隐私/偏见风险评估报告", "P1"), ("人机安全交互说明", "P2"),
      ("模型卡片(训练数据/偏差披露)", "P2"),
    ],
    "local_duty": "判断该 AI 功能在整车或运营场景中的最终用途,确认是否落入高风险场景。",
    "gap": "需确认 ADAS/座舱情感识别是否触发高风险义务;缺少可解释性与人类监督记录。",
    "scenarios": ["出行平台", "企业通勤", "政府公务"],
  },
  {
    "regulation_id": "REG-004",
    "name": "UNECE R155 车辆网络安全",
    "official_number": "UN R155 / CSMS",
    "issuer": "UNECE WP.29",
    "type": "网络安全",
    "scope": "EU + 英国等 60+ 缔约方",
    "applicable_product": ["整车", "车联网系统"],
    "effective_date": "2024-07-01(所有新生产车强制)",
    "impact_level": "高",
    "core_requirement": "组织级 CSMS 证书(有效期 ≤3 年)+ 车辆型式认证;须做 TARA 威胁分析、全生命周期监测与供应链网络安全,参照 ISO/SAE 21434。",
    "official_source": "https://unece.org/sites/default/files/2023-02/R155e%20%282%29.pdf",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("CSMS 网络安全管理体系证书", "P0"), ("TARA 整车威胁风险评估报告", "P0"),
      ("漏洞发现/通报/响应流程", "P1"), ("接口安全说明", "P1"), ("渗透测试报告", "P2"),
    ],
    "local_duty": "负责整车层面网络安全认证与型式认证提交。",
    "gap": "需确认 TARA 是否覆盖中国方提供的系统,以及能否对接本地整车厂 CSMS 体系。",
    "scenarios": ["公共交通", "物流运输", "政府公务", "出行平台", "企业通勤"],
  },
  {
    "regulation_id": "REG-005",
    "name": "UNECE R156 软件更新管理",
    "official_number": "UN R156 / SUMS",
    "issuer": "UNECE WP.29",
    "type": "网络安全",
    "scope": "EU + 英国等 60+ 缔约方",
    "applicable_product": ["整车", "OTA 系统"],
    "effective_date": "2024-07-01",
    "impact_level": "中",
    "core_requirement": "软件更新过程需可控、可追溯、可安全回滚;要求 SUMS 软件更新管理体系认证与 OTA 流程合规。",
    "official_source": "https://unece.org/transport/documents/2021/03/standards/un-regulation-no-156-software-update-and-software-update-management",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("SUMS 软件更新管理体系说明", "P0"), ("OTA 更新流程文件", "P1"),
      ("软件版本记录", "P1"), ("回滚机制说明", "P2"),
    ],
    "local_duty": "负责整车级软件更新认证和客户交付说明。",
    "gap": "需确认中国方软件更新流程能否纳入本地合作方 SUMS 体系;发布/回滚责任边界待明确。",
    "scenarios": ["公共交通", "出行平台", "企业通勤"],
  },
  {
    "regulation_id": "REG-006",
    "name": "GDPR + EU 数据法案 Data Act",
    "official_number": "(EU) 2023/2854",
    "issuer": "欧盟委员会",
    "type": "数据与AI",
    "scope": "EU 全域",
    "applicable_product": ["整车", "车队平台", "车联网"],
    "effective_date": "2025-09-12(数据法案适用)",
    "impact_level": "高",
    "core_requirement": "数据法案 2025/09 起适用:联网车数据须可携带、用户可授权第三方访问;叠加 GDPR 与 NIS2 联网车风险评估。",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32023R2854",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("数据流图与数据字段清单", "P0"), ("DPIA 数据保护影响评估", "P0"),
      ("跨境传输说明(SCC/BCR)", "P0"), ("第三方访问授权机制", "P1"), ("EU 数据驻留说明", "P1"),
    ],
    "local_duty": "面向终端客户/运营商的数据合规告知与合同安排,确认 controller/processor 角色。",
    "gap": "数据主权是政企采购隐形一票否决项;即便云在欧盟,若数据可被境外远程访问也会被质疑。",
    "scenarios": ["政府公务", "公共交通", "出行平台", "企业通勤"],
  },
]
REGULATIONS += [
  {
    "regulation_id": "REG-007",
    "name": "CBAM 碳边境调节机制",
    "official_number": "(EU) 2023/956",
    "issuer": "欧盟委员会",
    "type": "碳合规",
    "scope": "EU 进口",
    "applicable_product": ["上游材料(钢/铝)", "供应链"],
    "effective_date": "2026-01-01(正式征收)",
    "impact_level": "中",
    "core_requirement": "2026 起正式征收;当前重点覆盖钢铁、铝、水泥、化肥、氢、电力等上游材料,影响汽车供应链碳成本与碳数据披露。",
    "official_source": "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism_en",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("Scope3 全产业链碳核算证明", "P1"), ("上游钢/铝等材料碳数据", "P1"),
      ("第三方碳核查报告", "P2"), ("年度碳排放申报台账", "P2"),
    ],
    "local_duty": "欧盟碳账户开户、CBAM 年度申报清缴、碳核查对接。",
    "gap": "注意:CBAM 当前并非'所有整车/电池进口强制',而是影响上游材料碳成本;整车碳足迹溯源链条尚不完整。",
    "scenarios": ["物流运输", "公共交通"],
  },
  {
    "regulation_id": "REG-008",
    "name": "Euro 7 排放与电池耐久法规",
    "official_number": "(EU) 2024/1257",
    "issuer": "欧盟委员会",
    "type": "排放合规",
    "scope": "EU 全域",
    "applicable_product": ["整车", "商用车"],
    "effective_date": "2026-11-29(新车型强制)",
    "impact_level": "中",
    "core_requirement": "2026 年末起新车型强制;收紧刹车/轮胎颗粒物排放,新增动力电池 8 年 72% 容量保有最低标准。",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=OJ:L_202401257",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("整车颗粒物排放检测报告", "P1"), ("零排放车队达标证明", "P1"),
      ("动力电池耐久性能核验文件", "P1"), ("尾气监控系统合规说明", "P2"),
    ],
    "local_duty": "负责整车环保型式认证与市场准入。",
    "gap": "电池耐久检测报告与制动/轮胎颗粒物检测尚未按欧洲最新标准完成。",
    "scenarios": ["物流运输", "公共交通", "企业通勤"],
  },
  {
    "regulation_id": "REG-009",
    "name": "EU CO₂ 乘用车/货车排放标准",
    "official_number": "CO₂ Standards",
    "issuer": "欧盟委员会",
    "type": "排放合规",
    "scope": "EU 全域",
    "applicable_product": ["乘用车", "van"],
    "effective_date": "2025 / 2030 / 2035 三阶段",
    "impact_level": "高",
    "core_requirement": "2025-2029 较 2021 基准减排 15%;2030 乘用车-55%、van-50%;2035 起新乘用车和 van 100% 减排(禁售燃油新车)。",
    "official_source": "https://climate.ec.europa.eu/eu-action/transport-decarbonisation/road-transport/cars-and-vans_en",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("车队 TCO 与减排测算模板", "P1"), ("车型 CO₂ 达标数据", "P1"),
      ("分场景减排话术(公务/出租/物流)", "P2"),
    ],
    "local_duty": "负责整车投标中的绿色采购响应文件。",
    "gap": "需按乘用车/van/公交分别设计产品组合,不能用单一车型覆盖所有场景。",
    "scenarios": ["企业通勤", "出行平台", "政府公务", "物流运输"],
  },
  {
    "regulation_id": "REG-010",
    "name": "Regulation 2018/858 整车型式认证 WVTA",
    "official_number": "(EU) 2018/858",
    "issuer": "欧盟委员会",
    "type": "准入认证",
    "scope": "EU 全域",
    "applicable_product": ["整车"],
    "effective_date": "2020-09-01(M1 类认证有效期约 7 年)",
    "impact_level": "高",
    "core_requirement": "整车进入欧洲市场需完成整车型式认证(WVTA)、CoC 合格证与市场监督要求。",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32018R0858",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("整车型式认证 WVTA 文件", "P0"), ("CoC 合格证", "P0"),
      ("零部件/系统技术文件与测试报告", "P1"), ("供应商声明", "P2"),
    ],
    "local_duty": "负责整车型式认证、CoC、CoP 和市场准入文件。",
    "gap": "需确认中国方技术变更是否触发整车重新认证或补充测试。",
    "scenarios": ["公共交通", "物流运输", "政府公务", "出行平台", "企业通勤"],
  },
  {
    "regulation_id": "REG-011",
    "name": "Clean Vehicles Directive 清洁车辆指令",
    "official_number": "(EU) 2019/1161",
    "issuer": "欧盟委员会",
    "type": "公共采购",
    "scope": "EU 公共采购",
    "applicable_product": ["公交", "公务车", "整车"],
    "effective_date": "2021-08-02",
    "impact_level": "中",
    "core_requirement": "公共采购设定清洁/零排放车辆最低采购比例,关注低排放、TCO 与环境表现。",
    "official_source": "https://transport.ec.europa.eu/transport-themes/clean-transport/clean-vehicles-directive_en",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("电池能耗与电驱效率数据", "P0"), ("减排测算支持", "P1"), ("TCO 输入数据", "P1"),
    ],
    "local_duty": "负责整车投标中的绿色采购响应文件。",
    "gap": "需提供客户可用的能耗、减排和成本测算数据,以支撑绿色采购评分。",
    "scenarios": ["公共交通", "政府公务"],
  },
  {
    "regulation_id": "REG-012",
    "name": "Foreign Subsidies Regulation 外国补贴条例",
    "official_number": "(EU) 2022/2560",
    "issuer": "欧盟委员会",
    "type": "公共采购",
    "scope": "EU 公共采购",
    "applicable_product": ["整车", "大型采购"],
    "effective_date": "2023-10-12",
    "impact_level": "中",
    "core_requirement": "大型公共采购可能要求披露第三国财政资助(补贴/贷款/担保)。",
    "official_source": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022R2560",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("Foreign Financial Contributions 清单", "P1"), ("补贴/贷款/担保说明", "P1"),
      ("联合投标责任说明", "P2"),
    ],
    "local_duty": "判断项目是否触发 FSR 申报,并组织投标文件提交。",
    "gap": "需确认项目金额和合作结构是否触发 FSR 披露义务;中国方信息是否需纳入本地方申报。",
    "scenarios": ["公共交通", "政府公务"],
  },
]
REGULATIONS += [
  {
    "regulation_id": "REG-013",
    "name": "General Safety Regulation 通用安全法规",
    "official_number": "(EU) 2019/2144",
    "issuer": "欧盟委员会",
    "type": "准入认证",
    "scope": "EU 全域",
    "applicable_product": ["整车", "ADAS"],
    "effective_date": "2024-07-07",
    "impact_level": "高",
    "core_requirement": "车辆需满足欧盟通用安全与先进安全系统(ADAS)强制装配要求。",
    "official_source": "https://eur-lex.europa.eu/eli/reg/2019/2144/oj",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("ADAS 功能说明与安全测试报告", "P0"), ("功能安全材料(ISO 26262)", "P1"),
      ("系统边界说明", "P2"),
    ],
    "local_duty": "负责整车安全认证和最终安全性能声明。",
    "gap": "中国方系统与整车安全功能责任边界待厘清;测试报告需符合本地客户要求。",
    "scenarios": ["公共交通", "政府公务", "出行平台", "企业通勤"],
  },
  {
    "regulation_id": "REG-014",
    "name": "Euro NCAP 2026 安全评估协议",
    "official_number": "Euro NCAP 2026",
    "issuer": "Euro NCAP 联盟",
    "type": "安全测评",
    "scope": "EU 全域",
    "applicable_product": ["整车"],
    "effective_date": "2026-01-01(逐年更新)",
    "impact_level": "中",
    "core_requirement": "2026 起四阶段评分(Safe Driving/Crash Avoidance/Crash Protection/Post-Crash),每项 0-100%,评级受最低分项影响。",
    "official_source": "https://www.euroncap.com/protocols/",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("整车结构碰撞与 ADAS 实验数据", "P1"), ("样车量产一致性文件", "P1"),
      ("评级投标使用权说明", "P2"),
    ],
    "local_duty": "对接 NCAP 实验室、排期报备,验证评级、宣发与申诉。",
    "gap": "车型未适配欧洲最新测试标准;缺少本地前置摸底,ADAS 适配数据可能限制渠道与投标准入。",
    "scenarios": ["政府公务", "出行平台", "企业通勤", "公共交通"],
  },
  {
    "regulation_id": "REG-015",
    "name": "REACH / SVHC 化学品合规",
    "official_number": "(EC) 1907/2006",
    "issuer": "ECHA",
    "type": "材料合规",
    "scope": "EU 全域",
    "applicable_product": ["零部件", "电池", "内饰"],
    "effective_date": "持续生效",
    "impact_level": "低",
    "core_requirement": "材料和化学品需满足欧盟限制物质要求;高关注物质(SVHC)须申报。",
    "official_source": "https://echa.europa.eu/regulations/reach/understanding-reach",
    "last_verified_at": "2026-07-10",
    "status": "已审核",
    "version": "v1.0",
    "provide": [
      ("REACH / SVHC 声明", "P1"), ("材料成分说明", "P2"), ("供应商合规声明", "P2"),
    ],
    "local_duty": "将供应商声明纳入整车或零部件合规文件。",
    "gap": "需确认所有出口零部件和维修备件是否已有材料合规声明,上游数据可追溯性待补。",
    "scenarios": ["物流运输", "公共交通", "企业通勤"],
  },
  {
    "regulation_id": "REG-016",
    "name": "德国联邦补贴与本地化认证要求(示例·成员国差异)",
    "official_number": "DE-KBA / BAFA",
    "issuer": "德国 KBA / BAFA",
    "type": "准入认证",
    "scope": "成员国:德国",
    "applicable_product": ["整车", "公交", "车队"],
    "effective_date": "2026 起补贴退坡、本地证明要求收紧",
    "impact_level": "高",
    "core_requirement": "德国在 EU 框架上叠加本地补贴申领条件、本地化生产/维保证明与充电配套证明要求,补贴退坡后门槛提高。",
    "official_source": "https://www.bafa.de/",
    "last_verified_at": "2026-07-15",
    "status": "待审核",
    "version": "v0.9",
    "provide": [
      ("德国本地维保网络覆盖证明", "P0"), ("本地化生产/组装说明", "P1"),
      ("充电配套(AFIR)证明", "P1"), ("补贴申领资质文件", "P2"),
    ],
    "local_duty": "负责德国本地补贴申领、维保网络落地与本地化证明。",
    "gap": "成员国差异法规尚未系统收集;德国本地维保覆盖与补贴口径需专人跟踪(对应导师场景03:政策变化驱动经营调整)。",
    "scenarios": ["公共交通", "政府公务", "企业通勤"],
  },
]



